$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI = "http://devads/DefaultCollection/"
$env:SYSTEM_TEAMPROJECT = "B"
$env:BUILD_REPOSITORY = "Playground"
$env:BUILD_BUILDID = "2565"
$env:SYSTEM_ACCESSTOKEN = "2vdfrhez7iyjy64yrep7eldqcqlijh5f6z23o5pvv4yj3x7g6imq"